config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :users

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  delegate :name, to: :user, prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @name = "Pedro"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_path
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    end
  end

  def destroy
    @user = User.find(params[:id])

    @user.destroy

    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Hello <%= @name %>!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.label :user_id %>
    <%= f.select :user_id, User.all.collect { |u| [u.name, u.id] }, include_blank: true %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post #<%= @post.id %></h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
  <article>
    <h2><%= post.title %></h2>
    <% post.body&.lines&.each do |line| %>
      <p><%= line %></p>
    <% end %>
    <footer>
      <%= link_to "Edit", edit_post_path(post) %>
      <%= link_to "Destroy", post, method: :delete %>
    </footer>
  </article>
<% end %>

<% if @posts.empty? %>
  <p><em>There are no posts</em></p>
<% end %>

<%= link_to "New post", new_post_path %></li>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<% @post.body&.lines&.each do |line| %>
  <p><%= line %></p>
<% end %>

<% if @post.user.present? %>
  by <%= link_to @post.user_name, @post.user %>
<% end %>

<ul>
  <li>
    <strong>ID</strong>
    <br>
    <%= @post.id %></li>
  </li>
  <li>
    <strong>Created at</strong>
    <br>
    <%= @post.created_at %>
  </li>
  <li>
    <strong>Last updated at</strong>
    <br>
    <%= @post.updated_at %>
  </li>
</ul>

<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Destroy", @post, method: :delete %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user %></td>
        <td><%= link_to "Edit", edit_user_path(user) %></td>
        <td><%= link_to "Destroy", user, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<ul>
  <li>
    <strong>ID</strong>
    <br>
    <%= @user.id %></li>
  </li>
  <li>
    <strong>Name</strong>
    <br>
    <%= @user.name %>
  </li>
  <li>
    <strong>Created at</strong>
    <br>
    <%= @user.created_at %>
  </li>
  <li>
    <strong>Last updated at</strong>
    <br>
    <%= @user.updated_at %>
  </li>
</ul>

<h2>Posts</h2>

<% @user.posts.each do |post| %>
  <article>
    <h2><%= link_to post.title, post %></h2>
    <% post.body&.lines&.each do |line| %>
      <p><%= line %></p>
    <% end %>
  </article>
<% end %>

<%= link_to "Edit", edit_user_path(@user) %>
<%= link_to "Destroy", @user, method: :delete %>